### ISSUE TITLE
Game crashes as soon as I open the Atlas.

### ISSUE THREAD

**Issue by rbdej** [Pepperoni-Jabroni/MapAtlases#20]
I play in a Minecraft 1.18.1 Fabric server with my friends. We installed the mod and at one point I have an Atlas that crashes my client. Only I got the bugged Atlas. Anyways, here's the crash report:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 25/12/2021, 7:46 pm
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "id" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.getMapIntFromString(MapAtlasesAccessUtils.java:61)
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.createMapItemStackFromStrId(MapAtlasesAccessUtils.java:55)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.drawBackground(MapAtlasesAtlasOverviewScreen.java:78)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.render(MapAtlasesAtlasOverviewScreen.java:43)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:875)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.getMapIntFromString(MapAtlasesAccessUtils.java:61)
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.createMapItemStackFromStrId(MapAtlasesAccessUtils.java:55)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.method_2389(MapAtlasesAtlasOverviewScreen.java:78)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.method_25394(MapAtlasesAtlasOverviewScreen.java:43)

-- Screen render details --
Details:
	Screen name: pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen
	Mouse location: Scaled: (320, 169). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kahel02'/5206, l='ClientLevel', x=544.87, y=78.00, z=-264.82]]
	Chunk stats: 1024, 316
	Level dimension: minecraft:overworld
	Level spawn location: World: (19,63,38), Section: (at 3,15,6 in 1,3,2; chunk contains blocks 16,-64,32 to 31,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 65224206 game time, 122208 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks_r505296.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3614274080 bytes (3446 MiB) / 4093640704 bytes (3904 MiB) up to 10502537216 bytes (10016 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2503
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27319.00
	Virtual memory used (MB): 21507.46
	Swap memory total (MB): 10989.02
	Swap memory used (MB): 282.59
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx10001M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.2.60
		bedrockwaters: BedrockWaters 1.6.0+1.18.1
		betterpingdisplay: Better Ping Display 1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.0.45
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		crowdin-translate: CrowdinTranslate 1.4+1.18
		effective: Effective 1.0
		enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.11
		fabrictailor: Fabric Tailor 1.7.3
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		ferritecore: FerriteCore 4.0.0
		fpsreducer: FPS Reducer 1.25-mc1.18
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		iris: Iris 1.1.3
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lithium: Lithium 0.7.6
		logical_zoom: Logical Zoom 0.0.13
		map_atlases: Map Atlases 1.3.2
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pling: Pling 1.5.0
		roughlyenoughitems: Roughly Enough Items 7.1.356
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		smoothboot: Smooth Boot 1.18-1.7.0
		smoothswapping: Smooth Swapping 0.4.3
		sodium: Sodium 0.4.0-alpha5+build.9
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		trajectory-preview: Trajectory Preview 1.0-1.18.1
		transportables: Transportables 1.1
	Launched Version: Fabric 1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r505296.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Map Atlases (map_atlases)

**Comment by rbdej** [comment]
OK I *think* I know how to recreate it.

When I log in to our minecraft 1.18.1 server, there's a chance that the mini-map doesn't load or render in the player's screen. When that happens, if a player opens the Atlas map item, the game will crash. Here's another crash report from when I noticed this pattern.


---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 25/12/2021, 10:18 pm
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "id" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.getMapIntFromString(MapAtlasesAccessUtils.java:61)
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.createMapItemStackFromStrId(MapAtlasesAccessUtils.java:55)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.drawBackground(MapAtlasesAtlasOverviewScreen.java:78)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.render(MapAtlasesAtlasOverviewScreen.java:43)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:875)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.getMapIntFromString(MapAtlasesAccessUtils.java:61)
	at pepjebs.mapatlases.utils.MapAtlasesAccessUtils.createMapItemStackFromStrId(MapAtlasesAccessUtils.java:55)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.method_2389(MapAtlasesAtlasOverviewScreen.java:78)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.method_25394(MapAtlasesAtlasOverviewScreen.java:43)

-- Screen render details --
Details:
	Screen name: pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen
	Mouse location: Scaled: (320, 169). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 3 total; [class_746['Kahel02'/58099, l='ClientLevel', x=1056.10, y=65.00, z=-510.96], class_745['Erik_Faringer'/57797, l='ClientLevel', x=1050.56, y=65.00, z=-511.93], class_745['CiaIsAmazing'/58184, l='ClientLevel', x=998.28, y=65.09, z=-432.11]]
	Chunk stats: 1024, 321
	Level dimension: minecraft:overworld
	Level spawn location: World: (19,63,38), Section: (at 3,15,6 in 1,3,2; chunk contains blocks 16,-64,32 to 31,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 65406432 game time, 380498 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks_r505296.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5366436656 bytes (5117 MiB) / 5939134464 bytes (5664 MiB) up to 10502537216 bytes (10016 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2503
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29180.14
	Virtual memory used (MB): 23183.99
	Swap memory total (MB): 12850.16
	Swap memory used (MB): 295.11
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx10001M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.2.60
		betterpingdisplay: Better Ping Display 1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.0.45
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		crowdin-translate: CrowdinTranslate 1.4+1.18
		effective: Effective 1.0
		enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.11
		fabrictailor: Fabric Tailor 1.7.3
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		ferritecore: FerriteCore 4.0.0
		fpsreducer: FPS Reducer 1.25-mc1.18
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		iris: Iris 1.1.3
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lithium: Lithium 0.7.6
		logical_zoom: Logical Zoom 0.0.13
		map_atlases: Map Atlases 1.3.2
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pling: Pling 1.5.0
		roughlyenoughitems: Roughly Enough Items 7.1.356
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		smoothboot: Smooth Boot 1.18-1.7.0
		smoothswapping: Smooth Swapping 0.4.3
		sodium: Sodium 0.4.0-alpha5+build.9
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		transportables: Transportables 1.1
	Launched Version: Fabric 1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r505296.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Map Atlases (map_atlases)

**Comment by Pepperoni-Jabroni** [comment]
Thank you very much for the detailed report and sorry about the poor user experience!

**Comment by rbdej** [comment]
All g 😊, we understand that developing stuff can be hard at times. It's a really nice mod and we hope the logs we provided can help you guys out, good luck! 😄

**Comment by Pepperoni-Jabroni** [comment]
I never closed this out, but the Screen no longer relies on createMapItemStackFromStrId, so this is resolved. Thanks for reporting!
