### ISSUE TITLE
Out of bounds disconnect

### ISSUE THREAD

**Issue by DynamicMountain** [Pepperoni-Jabroni/MapAtlases#29]
Running on 1.18.2 in a modpack, upon creating a map atlas, and placing it within my inventory, kicks me out of the world with this error. Trying to reconnect to the singleplayer world gives the same error every time. I did not interact with the map, other than it being in my inventory, and the minimap being active in the top right

Encountered exception while handling in channel with name "map_atlases:map_atlas_sync"
java.lang.ArrayIndexOutOfBoundsException: Index 112 out of bounds for length 27
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.network.PacketByteBuf.readEnumConstant(PacketByteBuf:332)
	at net.minecraft.network.packet.s2c.play.MapUpdateS2CPacket.method_34137(MapUpdateS2CPacket:36)
	at net.minecraft.network.PacketByteBuf.readCollection(PacketByteBuf:123)
	at net.minecraft.network.PacketByteBuf.readList(PacketByteBuf:136)
	at net.minecraft.network.packet.s2c.play.MapUpdateS2CPacket.<init>(MapUpdateS2CPacket:35)
	at pepjebs.mapatlases.lifecycle.MapAtlasesClientLifecycleEvents.mapAtlasClientSync(MapAtlasesClientLifecycleEvents.java:55)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39)
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89)
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$cpb000$handleCustomPayload(ClientPlayNetworkHandler:2432)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler)
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:60)
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:8)
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:172)
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:157)
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:55)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:833)

**Comment by Pepperoni-Jabroni** [comment]
Thanks very much for the report - I'll take a look at this in a day or two when I update to 1.19

**Comment by OuroborosBoy** [comment]
I'm also experiencing this with version 1.4.0 on mc 1.19. When it kicks me, for some reason it goes back to the multiplayer server list page, even though I'm attempting to reload a single-player world. Not sure if this is helpful, but I'll include my latest log file.
[latest.log](https://github.com/Pepperoni-Jabroni/MapAtlases/files/8888778/latest.log)

**Comment by Pepperoni-Jabroni** [comment]
This is fixed as of v2.0.1 - I added a try/catch to avoid the Exception crashing the client. If you see the Warning "Bad Minecraft MapUpdate packet sent to client by server" printed to your LOG, could you upload it here? I'm trying to repro this issue - thanks!
