### ISSUE TITLE
Crash when in Atlas GUI while flying into newly-mapped area with Elytra

### ISSUE THREAD

**Issue by Pepperoni-Jabroni** [Pepperoni-Jabroni/MapAtlases#5]
Log w/ Stacktrace: https://paste.ee/p/MT7kB

```
java.lang.NullPointerException: Rendering screen
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.method_2389(MapAtlasesAtlasOverviewScreen.java:86)
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreen.method_25394(MapAtlasesAtlasOverviewScreen.java:52)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Pepperoni-Jabroni** [comment]
This was addressed with revision 483630494 and built into V1.2.3.
