### ISSUE TITLE
Fabric 1.19 REI CRASH

### ISSUE THREAD

**Issue by MrJorman** [Pepperoni-Jabroni/MapAtlases#50]
[crash-2022-07-12_15.06.25-client.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/9092611/crash-2022-07-12_15.06.25-client.txt)

**Comment by TheCherry** [comment]
Got exact the same error.
<details>
<summary>Click me</summary>
---- Minecraft Crash Report ----
// Why did you do that?

Time: 12.07.22, 19:43
Description: Rendering entry

java.lang.NullPointerException: Cannot read field "field_6002" because "entity" is null
	at pepjebs.mapatlases.client.MapAtlasesClient.getPredicateForAtlas(MapAtlasesClient.java:86)
	at net.minecraft.class_6395.call(class_6395.java:14)
	at net.minecraft.class_806.method_3495(class_806.java:80)
	at net.minecraft.class_918.method_4019(class_918.java:259)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getExtraData(ItemEntryDefinition.java:253)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:258)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.render(ForwardingEntryRenderer.java:42)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:200)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:409)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.drawCurrentEntry(EntryListStackEntry.java:144)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:364)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:246)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:139)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:90)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:210)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:784)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:680)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$21(RoughlyEnoughItemsCoreClient.java:415)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy122.render(Unknown Source)
	at net.minecraft.class_757.handler$zfa000$renderScreenPost(class_757.java:8084)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pepjebs.mapatlases.client.MapAtlasesClient.getPredicateForAtlas(MapAtlasesClient.java:86)
	at net.minecraft.class_6395.call(class_6395.java:14)
	at net.minecraft.class_806.method_3495(class_806.java:80)
	at net.minecraft.class_918.method_4019(class_918.java:259)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getExtraData(ItemEntryDefinition.java:253)

-- Screen details --
Details:
	Screen name: badasintended.slotlink.client.gui.screen.RequestScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:202)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:409)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.drawCurrentEntry(EntryListStackEntry.java:144)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:364)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:246)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:139)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:90)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:210)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:784)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:680)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$21(RoughlyEnoughItemsCoreClient.java:415)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy122.render(Unknown Source)
	at net.minecraft.class_757.handler$zfa000$renderScreenPost(class_757.java:8084)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: map_atlases:atlas

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: atlas
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: badasintended.slotlink.client.gui.screen.RequestScreen

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Z level: 0
	Bounds: me.shedaniel.math.Rectangle@19c4e20e[height=18,width=18,x=776,y=243]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: map_atlases:atlas

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: atlas
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: badasintended.slotlink.client.gui.screen.RequestScreen

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.15.46-1-lts
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 598663240 bytes (570 MiB) / 6442450944 bytes (6144 MiB) up to 10586423296 bytes (10096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258,00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 27972,18
	Virtual memory used (MB): 14094,49
	Swap memory total (MB): 20000,00
	Swap memory used (MB): 2149,61
	JVM Flags: 3 total; -Xss1M -Xms1024M -Xmx10096M
	Fabric Mods: 
		additionalbanners: AdditionalBanners 8.0.2
		adorn: Adorn 3.5.4+1.19
		advancementplaques: Advancement Plaques 1.4.5
		ae2: Applied Energistics 2 12.0.1-alpha
		ae2wtlib: AE2WTLib 12.0.1-alpha
		ambientsounds: Ambiend Sounds (Fabric) 5.2.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.9.30
		artifacts: Artifacts 7.1.1+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		autoconfig1u: Auto Config v1 Updated 3.4.0
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 2.0.13
		betteranimalsplus: Better Animals Plus 1.19-11.0.6
		betterend: Better End 2.0.9
		betterf3: BetterF3 1.3.1
		bettermending: Better Mending 1.4.1
		betternether: Better Nether 7.0.6
		bitsandchisels: BitsAndChisels 2.7.0
			stacc: Stacc 1.3.4
		blockus: Blockus 2.5.1+1.19
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		bookshelf: Bookshelf 14.1.7
		byg: Oh The Biomes You'll Go 2.0.0.6
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		charmonium: Charmonium 4.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		computercraft: CC: Restitched 1.101.0
			cloth-utils-v1: Cloth Utils v1 2.0.54
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		conjuring: Conjuring 1.0.23+1.19
		controlling: Controlling For Fabric 10.0+3
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		creativecore: CreativeCore (Fabric) 2.7.2
		dawn: Dawn API 3.5.0
		dustrial_decor: Dustrial Decor 0.5
		edenring: EdenRing 0.6.3
		ellemes_container_lib: Ellemes' Container Library 2.0.1
		enchdesc: EnchantmentDescriptions 11.0.5
		endrem: End Remastered 5.1.0
		entitybanners: Entity Banners 1.1-BETA+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		expandedstorage: Expanded Storage 8.0.1
		extendedcopper: Extended Copper 1.0.0
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricenchantments: Fabric Enchantments 0.8.0
		fabricloader: Fabric Loader 0.14.8
		fallingtree: FallingTree 3.7.1
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmersknives: Farmer's Knives 2.0
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		glassdoor: Glass Doors 3.0.0-rc.1+1.19
		graveyard: The Graveyard 1.10
		graveyard_biomes: The Graveyard Biomes 1.2
			omega-config: OmegaConfig 1.2.2-1.18.1
		headindex: Head Index 1.0.8
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.0+1.19
		highlighter: Highlighter 1.1.2
		ias: In-Game Account Switcher 7.2.0
		iceberg: Iceberg 1.0.38
		immersive_portals: Immersive Portals 2.0.4
			imm_ptl_core: Immersive Portals Core 2.0.4
			q_misc_util: QMiscUtil 2.0.4
		indium: Indium 1.0.6+mc1.19
		inventoryprofilesnext: Inventory Profiles Next 1.6.0
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemborders: Item Borders 1.1.6
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		lcsl: Lightly Colored Sea Lanterns 1.1.0
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.8.1
		lootr: Lootr 0.3.20.58
		map_atlases: Map Atlases 2.0.0
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.6
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 8.1.0
			megane-api: megane-api 8.1.0
			megane-fabric-transfer: megane-fabric-transfer 8.1.0
			megane-reborn-energy: megane-reborn-energy 8.1.0
			megane-runtime: megane-runtime 8.1.0
			megane-vanilla: megane-vanilla 8.1.0
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		mo_glass: Mo Glass 1.6.1-MC1.19
		modern_industrialization: Modern Industrialization 1.3.1
			magna: Magna 1.8.0-1.19
			noindium: No Indium? 1.1.0+1.19
			playerabilitylib: Pal 1.6.0
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 4.0.3
		morebannerfeatures: More Banner Features 1.1.3
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		owo: oÏ‰o 0.7.3+1.19
		paginatedadvancements: Paginated Advancements 1.0.1
		paintings: Paintings++ 10.0.0.0
		palette256: Palette 256 1.0.0
		patchouli: Patchouli 1.19-74-FABRIC
			fiber: fiber 0.23.0-2
		phosphor: Phosphor 0.8.1
		promenade: Promenade 2.7.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.0.0
		redbits: Red Bits 1.14.0
			interference: Interference API 1.4.2
		redstonebits: Redstone Bits 1.8.2
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		roughlyenoughitems: Roughly Enough Items 9.1.511
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		roughlysearchable: Roughly Searchable 2.5.0+1.19
		simple_shelves: Simple Shelves 1.0.6
		simple_utilities: Simple HUD Utilities 2.5.0
		slotlink: slotlink 5.0.0
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sparkle: Sparkle 1.0.0
		terrablender: TerraBlender 2.0.0.120
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tooltiprareness: Tooltip Rareness 1.0.6
		tooltiptweaks: Tooltip Tweaks 1.1.0
		transparent: Transparent 5.1.0
		travelersbackpack: Traveler's Backpack 1.19-8.0.1
		trinkets: Trinkets 3.4.0
		vanillatweaks: VanillaTweaks 1.5.60
		wands: Building Wands 2.5.3_beta_mc1.19
		wthit: wthit 5.5.1
		yigd: You're in Grave Danger 1.4.1
	Loaded Shaderpack: ComplementaryShaders_v4.5.zip
		Profile: VANILLA (+0 options changed by user)
</details>

**Comment by Pepperoni-Jabroni** [comment]
Will take a look this evening. Thanks for reporting!

**Comment by Pepperoni-Jabroni** [comment]
V2.0.1 fixes this: https://github.com/Pepperoni-Jabroni/MapAtlases/releases/tag/2.0.1
