### ISSUE TITLE
Crash on trying to open the atlas / right click on any block with the atlas book 1.19.2

### ISSUE THREAD

**Issue by URSFR** [Pepperoni-Jabroni/MapAtlases#70]
`---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-09-21 23:06:20
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'java.util.Map$Entry pepjebs.mapatlases.utils.MapAtlasesAccessUtils.getActiveAtlasMapStateServer(net.minecraft.class_1937, net.minecraft.class_1799, net.minecraft.class_3222)'
	at net.mehvahdjukaar.moonlight.api.integration.fabric.MapAtlasCompatImpl.getSavedDataFromAtlas(MapAtlasCompatImpl.java:26)
	at net.mehvahdjukaar.moonlight.api.integration.MapAtlasCompat.getSavedDataFromAtlas(MapAtlasCompat.java)
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.getMapData(MapHelper.java:30)
	at net.mehvahdjukaar.moonlight.api.map.MapHelper.toggleMarkersAtPos(MapHelper.java:112)
	at net.mehvahdjukaar.supplementaries.common.events.ItemsOverrideHandler$MapMarkerBehavior.tryPerformingAction(ItemsOverrideHandler.java:455)
	at net.mehvahdjukaar.supplementaries.common.events.ItemsOverrideHandler.tryPerformClickedBlockOverride(ItemsOverrideHandler.java:196)
	at net.mehvahdjukaar.supplementaries.common.events.ItemsOverrideHandler.tryPerformClickedBlockOverride(ItemsOverrideHandler.java:185)
	at net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:51)
	at net.mehvahdjukaar.supplementaries.common.events.fabric.ServerEventsFabric.onRightClickBlock(ServerEventsFabric.java:62)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_3225.handler$eep000$interactBlock(class_3225.java:4085)
	at net.minecraft.class_3225.method_14262(class_3225.java)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.handler$cfj000$modifiedRunLoop(MinecraftServer.java:5894)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting! This appears to be due to an issue with Supplementaries support based on the stacktrace. I'll look into whether the fix is on my side or their side. If its on their side, I'll still try to submit a PR to fix it for them. Maybe I changed the method signature and broke compatibility (which I didn't know they built specifically for my mod).

**Comment by Pepperoni-Jabroni** [comment]
Sorry - not Supplementaries, but Moonlight Lib.
