### ISSUE TITLE
[1.19.2] Multiplayer VarInt too big full map error

### ISSUE THREAD

**Issue by LittleLigr** [Pepperoni-Jabroni/MapAtlases#79]
Mini-map HUD works fine, but when somebody trying to open full map on server, it's just not open, I can only hear atlas open sound. If I will press F, atlas will play sound very fast and few seconds later server will crash.
When I try to open full map clien console print such log.

[11:19:45] [Render thread/ERROR]: Error executing task on Client
java.lang.RuntimeException: VarInt too big
	at net.minecraft.class_2540.method_10816(class_2540.java:446) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10800(class_2540.java:594) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_19772(class_2540.java:588) ~[client-intermediary.jar:?]
	at pepjebs.mapatlases.screen.MapAtlasesAtlasOverviewScreenHandler.<init>(MapAtlasesAtlasOverviewScreenHandler.java:29) ~[map-atlases-2.3.0+1.19.jar:?]
	at net.fabricmc.fabric.api.screenhandler.v1.ExtendedScreenHandlerType.create(ExtendedScreenHandlerType.java:95) ~[fabric-screen-handler-api-v1-1.3+1cc24b1b90-884026a9533836ba.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:80) ~[fabric-screen-handler-api-v1-1.3+1cc24b1b90-884026a9533836ba.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$onInitializeClient$0(ClientNetworking.java:54) ~[fabric-screen-handler-api-v1-1.3+1cc24b1b90-884026a9533836ba.jar:?]
	at net.minecraft.class_1255.redirect$beh000$redirectExecuteTask(class_1255.java:1021) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]

**Comment by LittleLigr** [comment]
However, everything works fine in singleplayer.

**Comment by LittleLigr** [comment]
Also, I noticed that after pressing alt+tab I can see full map, but it disapear when open game window again.
![image](https://user-images.githubusercontent.com/32247140/204478964-aac60051-dd98-48a2-9c96-7af27e41b91e.png)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting! Will take a look.
